festi/conference/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('conference.views',
    url(r'^$', 'index', name='index'),
)

festi/festi/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('account.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('conference.urls', namespace='conference')),
    url(r'', include('survey.urls', namespace='survey')),
)

urlpatterns += patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
)

festi/survey/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('survey.views',
    url(r'^(?P<event_slug>[\w-]+)/$', 'detail', name='detail'),
    url(r'^(?P<event_id>\d+)/form/$', 'form', name='form'),
    url(r'^(?P<event_slug>[\w-]+)/export/$', 'export', name='export'),
)

urlpatterns += patterns('',
    # url(r'^v1/', include('survey.api_v1', namespace='v1')),
)

festi/survey/models.py
# coding: utf8
import csv
from codecs import BOM_UTF8
import os
import random
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.encoding import force_unicode, smart_str
from jsonfield import JSONField


def random_name(instance, filename):
    cls_name = instance.__class__.__name__.lower()
    dirpath_format = cls_name + '/%Y/%m/%d/%H%M'
    dirpath = os.path.normpath(force_unicode(timezone.now().strftime(smart_str(dirpath_format))))
    random_name = ''.join(random.sample('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ' + '0123456789', 10))
    extension = os.path.splitext(filename)[-1]
    return dirpath + '_' + random_name + extension


class Base(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Event(Base):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=100, db_index=True)
    props = JSONField(verbose_name='Questions', blank=True)
    begin = models.DateTimeField()
    end = models.DateTimeField()
    is_public = models.BooleanField(default=False, db_index=True)
    is_closed = models.BooleanField(default=True, db_index=True)
    approve_email_content = models.TextField(blank=True, null=True, help_text=u'첫 줄은 제목')

    def __unicode__(self):
        return self.name

    def as_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'props': self.props,
            'begin': self.begin,
            'end': self.end,
        }

    def export_csv(self, f):
        header = ['email', 'name', 'gender', 'is_approved', 'is_notified', 'is_attended']


        f.write(BOM_UTF8)
        writer = csv.writer(f)
        writer.writerow([(col or '').encode('utf8') for col in header])

        for survey in self.survey_set.select_related('user').all():
            try:
                social = survey.user.socialaccount_set.first()
                name = social.extra_data['name']
                gender = social.extra_data['gender']
            except (AttributeError, KeyError):
                name = ''
                gender = ''

            row = [survey.user.email, name, gender, survey.is_approved, survey.is_notified, survey.is_attended]
            row.extend([prop['answer'] for prop in survey.props])
            writer.writerow([(col or '').encode('utf8') for col in row])

        return f


class Speaker(models.Model):
    event = models.ForeignKey(Event)
    idx = models.IntegerField(default=0)
    name = models.CharField(max_length=100)
    profile = models.CharField(max_length=100, blank=True)
    profile_image = models.ImageField(upload_to=random_name)
    keyword = models.CharField(max_length=20, blank=True)
    topic = models.CharField(max_length=100, blank=True)
    detail = models.TextField(blank=True)

    class Meta:
        ordering = ('idx', 'id')


class Survey(Base):
    event = models.ForeignKey(Event)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    props = JSONField()
    is_approved = models.BooleanField(default=False, db_index=True, verbose_name=u'승인여부')
    is_notified = models.BooleanField(default=False, db_index=True, verbose_name=u'알림여부')
    is_attended = models.BooleanField(default=False, db_index=True, verbose_name=u'참석여부')

    class Meta:
        unique_together = (('event', 'user'),)

    def as_dict(self):
        return {
            'props': self.props,
            'is_approved': self.is_approved,
            'is_notified': self.is_notified,
            'is_attended': self.is_attended,
        }

festi/survey/forms.py
# coding: utf8
from django import forms
from .widgets import SplitJSONWidget
from .models import Survey


class SurveyForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields = ('props',)
        widgets = {
            'props': SplitJSONWidget,
        }

    def clean_props(self):
        props = self.cleaned_data['props']
        for prop in props:
            if not prop.get('answer', '').strip():
                raise forms.ValidationError(u'모든 답변을 채워주세요.')
        return props

festi/survey/views.py
# coding: utf8
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from .forms import SurveyForm
from .models import Event, Speaker, Survey


def facebook_user_required(fn):
    def wrap(request, *args, **kwargs):
        facebook_account = request.user.socialaccount_set.filter(provider='facebook').first()
        if not facebook_account:
            messages.error(request, u'페이스북 유저가 아닙니다.')
            return redirect('account_logout')
        request.facebook_account = facebook_account

        return fn(request, *args, **kwargs)
    return login_required(wrap)


def index(request):
    return render(request, 'survey/index.html', {
    })


def detail(request, event_slug):
    event = get_object_or_404(Event, slug=event_slug)

    survey = None
    if request.user.is_authenticated():
        try:
            survey = Survey.objects.get(event=event, user=request.user)
        except Survey.DoesNotExist:
            pass

    speaker_list = Speaker.objects.filter(event=event).order_by('idx')

    return render(request, 'survey/detail.html', {
        'event': event,
        'survey': survey,
        'speaker_list': speaker_list,
    })


@facebook_user_required
def form(request, event_id):
    event = get_object_or_404(Event, id=event_id, is_public=True)

    try:
        survey = Survey.objects.get(event=event, user=request.user)
    except Survey.DoesNotExist:
        survey = None

    if request.method == 'POST':
        form = SurveyForm(request.POST, instance=survey)
        if form.is_valid():
            if not survey:
                survey = form.save(commit=False)
                survey.event = event
                survey.user = request.user
                messages.info(request, u'신청이 접수되었습니다.')
            else:
                survey = form.save(commit=False)
                messages.info(request, u'신청내역이 수정되었습니다.')
            survey.save()

            return redirect('conference:index')
        else:
            for error in form.errors['props']:
                messages.error(request, error)
    else:
        props = []
        if survey:
            props = survey.props

        for event_prop in (event.props or []):
            for prop in props:
                if int(prop['id']) == int(event_prop['id']):
                    if event_prop.get('answer_type', None):
                        prop['answer_type'] = event_prop['answer_type']
                    break
            else:
                prop = {
                    'id': event_prop['id'],
                    'question': event_prop['question'],
                    'answer': '',
                }
                if event_prop.get('answer_type', None):
                    prop['answer_type'] = event_prop['answer_type']
                props.append(prop)

        if not props:
            messages.info(request, u'참가신청 입력폼을 준비 중입니다.')
            return redirect('conference:index')

        props = sorted(props, key=lambda _p: int(_p['id']))

        form = SurveyForm(instance=survey, initial={'props': props})

    return render(request, 'survey/form.html', {
        'event': event,
        'survey': survey,
        'form': form,
        'avatar_url': request.facebook_account.get_avatar_url(),
    })


@login_required
def export(request, event_slug):
    if not request.user.is_superuser:
        return HttpResponse('Unauthorized', status=401)

    event = get_object_or_404(Event, slug=event_slug)

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="export.csv"'
    return event.export_csv(response)

festi/survey/templates/survey/detail.html
{% extends "survey/layout.html" %}

{% block content %}

<section class="bg-header bg-centerTop70 bg-cover">
    <div class="bg-filter sTop">
        <div class="container">
            <div class="jumbotron trn v-center">
                <h1>GDG Korea Android Conference</h1>
                <div class="space-sm"></div>
                <p>구글 캠퍼스 서울, 강남구 영동대로 417 오토웨이타워<br/>
                2015년 4월 18일 오후 1시 ~ 6시</p>
                <div class="space-sm"></div>

                {% if messages %}
                    {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}

                <ul class="list-inline">
                    {% if not survey %}
                        {# 페이스북 로그아웃 상태 #}
                        <li>
                            {% if not event.is_closed %}
                                <a href="{% url "survey:form" event.id %}" style="text-align: center; text-size: 3em;" class="btn btn-primary btn-xlg">
                                    <i class="fa fa-bolt"></i> 참가신청하기
                                </a>
                            {% else %}
                                <a style="text-align: center; text-size: 3em;" class="btn btn-default btn-xlg" disabled="disabled">
                                    <i class="fa fa-close"></i> 참가신청이 마감되었습니다.
                                </a>
                                <br/>
                                <a href="{% url "survey:form" event.id %}" style="text-align: center; text-size: 3em; padding-top: 2em;">
                                    승인여부 확인하기
                                </a>
                            {% endif %}
                        </li>
                    {% else %}
                        {# 페이스북 로그인 상태 #}
                        <li>
                            {% if survey.is_approved %}
                                <a style="text-align: center; text-size: 3em;" class="btn btn-success btn-xlg" disabled="disabled">
                                    승인되셨습니다. 컨퍼런스 때 뵐게요.
                                </a>
                            {% else %}
                                {% if not event.is_closed %}
                                    <a href="{% url "survey:form" event.id %}" style="text-align: center; text-size: 3em;" class="btn btn-default-trn btn-xlg">
                                        승인대기 중
                                    </a>
                                {% else %}
                                    <a style="text-align: center; text-size: 3em;" class="btn btn-default btn-xlg" disabled="disabled">
                                        {{ user }}님. 아쉽지만 다음 컨퍼런스에 함께 해요.
                                    </a>
                                {% endif %}
                            {% endif %}
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <h2 class="lg-title lg-title-border">일정</h2>
        <div class="row">
            <table class="table table-bordered" id="timetable">
                <thead>
                    <tr>
                        <th style="width: 200px;">시간</th>
                        <th style="width: 40%;">트랙 A</th>
                        <th style="width: 40%;">트랙 B</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>13:00 ~ 13:50</th>
                        <td colspan="2">UX/UI Guidelines for Android 2015 <span class="speaker">(임성혁)</span></td>
                    </tr>
                    <tr><td colspan="3">15분</td></tr>
                    <tr>
                        <th>14:05 ~ 14:55</th>
                        <td>go 언어로 안드로이드 앱 만들기 <span class="speaker">(박성재)</span></td>
                        <td>Android Looper <span class="speaker">(차영호)</span></td>
                    </tr>
                    <tr><td colspan="3">10분</td></tr>
                    <tr>
                        <th>15:05 ~ 15:55</th>
                        <td>테스트코드에서 코드 커버리지까지 <span class="speaker">(정승욱)</span></td>
                        <td>Kotlin for Android <span class="speaker">(허재위)</span></td>
                    </tr>
                    <tr><td colspan="3">15분</td></tr>
                    <tr>
                        <th>16:10 ~ 17:00</th>
                        <td>How we learned Android from Google <span class="speaker">(Hassan Abid)</span></td>
                        <td>RxAndroid <span class="speaker">(김용욱)</span></td>
                    </tr>
                    <tr><td colspan="3">10분</td></tr>
                    <tr>
                        <th>17:10 ~ 18:00</th>
                        <td>Battery - 안드로이드를 위한 쉬운 웹 API 호출 <span class="speaker">(박준규)</span></td>
                        <td>네이티브 크로스 플랫폼 개발 도구, Xamarin Forms를 사용한 MVVM 패턴과 테스팅 <span class="speaker">(이규원)</span></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <h2 class="lg-title lg-title-border">발표자</h2>
        <div class="row">
            {% for speaker in speaker_list %}
                {% if forloop.counter0|divisibleby:"3" %}
                    <div class="clearfix visible-md visible-lg" style="margin-bottom: 20px;"></div>
                {% endif %}
                {% if forloop.counter0|divisibleby:"2" %}
                    <div class="clearfix visible-sm" style="margin-bottom: 20px;"></div>
                {% endif %}
                <div class="col-md-4 col-lg-4 col-sm-6 wow fadeInLeft" data-wow-delay="0.8s">
                    <div class="panel panel-default text-center">
                        <div class="panel-body">
                            <img class="img-circle" src="{{ speaker.profile_image.url }}" style="width: 200px; margin: 10px 0;" />
                            <h3>{{ speaker.name }}</h3>
                            <p>{{ speaker.profile }}</p>
                        </div>
                        <div class="panel-footer">
                            <h4 class="text-center">{{ speaker.keyword }}</h4>
                            <p>{{ speaker.detail }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

<div class="bg-11 bg-cover bg-center">
    <div class="section-lg bg-filter-v2">
        <div class="container">
            <div id="testimonial" class="carousel slide" data-ride="carousel" data-interval="4000">
                <div class="carousel-inner">
                    <div class="item">
                        <div class="testimonial">
                            <p>"Every time you use a phone, or a computer, you use the ideas that Alan Turing invented. A hero."</p>
                            <div class="space-sm"></div>
                            <em>- Eric Schmidt</em>
                        </div>
                    </div>
                    <div class="item active">
                        <div class="testimonial">
                            <p>"Using RxJava to replace loaders and internal lib to replace fragments/activities. All that's left is views, android.animation.*, and bliss."</p>
                            <div class="space-sm"></div>
                            <em>- Jake Wharton</em>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimonial">
                            <p>"the definition of open: "mkdir android ; cd android ; repo init -u git://android.git.kernel.org/platform/manifest.git ; repo sync ; make"</p>
                            <div class="space-sm"></div>
                            <em>- Andy Rubin</em>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="section">
    <div class="container">
        <h2 class="lg-title lg-title-border">찾아오시는 길</h2>
        <div class="row">
            <p><img src="{{ STATIC_URL }}survey/google-campus-map.jpg" style="width: 100%;" /></p>
            <p>
                <a href="https://goo.gl/maps/rtUWW" target="_blank"><i class="fa fa-map-marker"></i> 구글 지도</a> &nbsp;
                <a href="http://map.daum.net/?urlX=514079&urlY=1113010&q=%EC%84%9C%EC%9A%B8+%EA%B0%95%EB%82%A8%EA%B5%AC+%EC%98%81%EB%8F%99%EB%8C%80%EB%A1%9C+417" target="_blank"><i class="fa fa-map-marker"></i> 다음 지도</a> &nbsp;
                <a href="http://map.daum.net/?urlX=514079&urlY=1113010&q=%EC%84%9C%EC%9A%B8+%EA%B0%95%EB%82%A8%EA%B5%AC+%EC%98%81%EB%8F%99%EB%8C%80%EB%A1%9C+417" target="_blank"><i class="fa fa-map-marker"></i> 네이버 지도</a>
            </p>
        </div>
    </div>
</section>

{% endblock %}

festi/survey/templates/survey/form.html
{% extends "survey/layout.html" %}

{% block header %}
{% endblock %}

{% block content %}
<style>
    body {
        padding-top: 60px;
    }
    #survey_form ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }
    #survey_form label {
        display: none;
    }
    #survey_form *[readonly=readonly] {
        background: #fff;
        border: 0;
    }
</style>

<div class="container">
    <div class="row">
        <div class="panel panel-success">
            <div class="panel-header text-center">
                <h3>
                    {% if not survey %}
                        {{ event.name }} 신청
                    {% else %}
                        {{ event.name }} 설문 수정
                    {% endif %}
                </h3>
            </div>
            <div class="panel-body">
                {% if survey.event.is_closed %}
                    {% if not survey.is_approved %}
                        <div class="alert alert-info">
                            {{ user }}님. 아쉽지만 다음 컨퍼런스에 함께 해요.
                        </div>
                    {% else %}
                        <div class="alert alert-success">승인되셨습니다. 컨퍼런스 때 뵐게요.</div>
                    {% endif %}
                {% else %}
                    {% if survey %}
                        {% if not survey.is_approved %}
                            <div class="alert alert-info">승인대기 중</div>
                        {% else %}
                            <div class="alert alert-success">승인되셨습니다. 컨퍼런스 때 뵐게요.</div>
                        {% endif %}
                    {% endif %}

                    <form id="survey_form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.props }}
                        </div>
                        <p class="text-right">
                            <input type="submit" value="입력완료" class="btn btn-primary" />
                        </p>
                    </form>
                {% endif %}
            </div>
            <div class="panel-footer">
                <a href="{% url "conference:index" %}">돌아가기</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

festi/survey/templates/survey/index.html
{% extends "survey/layout.html" %}

{% block react %}
<script type="text/jsx" src="{{ STATIC_URL }}/js/components/Common.jsx"></script>
<script type="text/jsx" src="{{ STATIC_URL }}/js/components/SurveyApp.jsx"></script>
{% endblock %}

festi/survey/templates/survey/layout.html
<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8" />
<title>{% block title %}GDG Korea Android{% endblock %}</title>
<meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no" />
<meta name="description" content="{{ event.name }}" />
<meta name="keywords" content="{{ event.name }}" />
<meta name="author" content="GDG Korea Android Team" />
<link rel="image_src" href="http://event.android.gdg.kr/static/festi/gkac3.jpg"/>
<meta property="fb:app_id" content="791867294202589" />
<meta property="og:title" content="GDG Korea Android"/>
<meta property="og:type" content="article"/>
<meta property="og:url" content="http://event.android.gdg.kr/3rd-GKAC/"/>
<meta property="og:description" content="{{ event.name }}"/>
<meta property="og:image" content="http://event.android.gdg.kr/static/festi/gkac3.jpg"/>
<meta property="og:image:width" content="800" />
<meta property="og:image:height" content="800" />
<meta property="article:author" content="https://www.facebook.com/GDG.Korea.Android" />
<link href="{{ STATIC_URL }}dragonfly/css/bootstrap.min.css" rel="stylesheet" />
<link href="{{ STATIC_URL }}dragonfly/css/themes/green.css" rel="stylesheet" />
<link href="{{ STATIC_URL }}dragonfly/css/slippry.min.css" rel="stylesheet" />
<link href="{{ STATIC_URL }}dragonfly/plugins/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" />
<link href="{{ STATIC_URL }}dragonfly/plugins/animate.css-master/animate.min.css" rel="stylesheet" />
<link href="{{ STATIC_URL }}survey/layout.css" rel="stylesheet" />
<link href="http://fonts.googleapis.com/css?family=Lato:300,400" rel="stylesheet" />
{% block extra_head %}{% endblock %}
</head>
<body>

{% block header %}
<nav class="navbar navbar-trn navbar-fixed-top" role="navigation" id="navbarSettings">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url "conference:index" %}">GDG Korea Android</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">
           </ul>
       </div>
    </div>
</nav>
<div id="navbarSpaceBottom"></div>
{% endblock %}

{% comment %}
{% if messages %}
<div class="container">
    <div class="row">
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endcomment %}

{% block content %}
{% endblock %}

{% block footer %}
<footer class="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-lg-4 col-xs-12">
                    <h4>공식 후원사</h4>
                    <ul class="info-list md-list i-primary">
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i>
                            <a>구글 코리아</a>
                        </li>
                    </ul>
                </div>
                <div class="space-sm visible-sm visible-xs"></div>

                <div class="col-md-4 col-lg-4 col-xs-12">
                    <h4>수고해주신 분들</h4>
                    <ul class="info-list md-list i-primary">
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i> 김용욱
                        </li>
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i> 김태호
                        </li>
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i> 김기완
                        </li>
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i> 이진석
                        </li>
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i> 임원균
                        </li>
                        <li>
                            <i class="fa fa-angle-right fa-fw"></i> 김나연
                        </li>
                    </ul>
                </div>
                <div class="space-sm visible-sm visible-xs"></div>
                <div class="col-md-4 col-lg-4  col-xs-12">
                    <h4>커뮤니티</h4>
                    <ul class="circle-icons icons-list">
                        <li>
                            <a href="https://plus.google.com/communities/100903743067544956282" title="GDG 코리아 안드로이드">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <p><a href="https://www.djangoproject.com/">Django</a>로 만든 <a href="https://github.com/gdgand/Festi">Festi</a>로 GDG 코리아 안드로이드 이벤트가 동작합니다.</p>
        </div>
    </div>

    <!--Back to top-->
    <a href="#" class="back-to-top">
        <i class="fa fa-angle-up"></i>
    </a>
</footer>
{% endblock %}

<script src="{{ STATIC_URL }}dragonfly/js/min/modernizr.custom.min.js"></script>
<script src="{{ STATIC_URL }}jquery/dist/jquery.min.js"></script>
<script src="{{ STATIC_URL }}jquery-ui/jquery-ui.min.js"></script>
<script src="{{ STATIC_URL }}bootstrap/dist/js/bootstrap.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/wow/0.1.6/wow.min.js"></script>
<script src="http://cdn.jsdelivr.net/jquery.knob/1.2.9/jquery.knob.min.js"></script>
<script src="{{ STATIC_URL }}dragonfly/js/min/slippry.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/mixitup/1.5.6/jquery.mixitup.min.js"></script>
<script src="http://cdn.jsdelivr.net/jquery.sticky/1.0.0/jquery.sticky.min.js"></script>
<script src="http://cdn.jsdelivr.net/jquery.nicescroll/3.5.4/jquery.nicescroll.min.js"></script>
<script src="{{ STATIC_URL }}dragonfly/js/min/contact-form.min.js"></script>
<script src="{{ STATIC_URL }}dragonfly/js/min/scripts.min.js"></script>
<!--[if lt IE 9]>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

{% block extra_script %}{% endblock %}

</body>
</html>